import localforage from 'localforage';

export const db = {
  profiles: localforage.createInstance({ name: 'hinov', storeName: 'profiles' }),
  clients: localforage.createInstance({ name: 'hinov', storeName: 'clients' }),
  quotes: localforage.createInstance({ name: 'hinov', storeName: 'quotes' }),
  sales: localforage.createInstance({ name: 'hinov', storeName: 'sales' }),
  commissions: localforage.createInstance({ name: 'hinov', storeName: 'commissions' }),
  installments: localforage.createInstance({ name: 'hinov', storeName: 'installments' }),
  prospects: localforage.createInstance({ name: 'hinov', storeName: 'prospects' }),
  prospectActivities: localforage.createInstance({ name: 'hinov', storeName: 'prospectActivities' }),
  prospectFollowUps: localforage.createInstance({ name: 'hinov', storeName: 'prospectFollowUps' }),
  activityReports: localforage.createInstance({ name: 'hinov', storeName: 'activityReports' }),
  weeklyReports: localforage.createInstance({ name: 'hinov', storeName: 'weeklyReports' }),
  categories: localforage.createInstance({ name: 'hinov', storeName: 'categories' }),
  services: localforage.createInstance({ name: 'hinov', storeName: 'services' }),
  prestations: localforage.createInstance({ name: 'hinov', storeName: 'prestations' }),
  settings: localforage.createInstance({ name: 'hinov', storeName: 'settings' }),
  syncQueue: localforage.createInstance({ name: 'hinov', storeName: 'syncQueue' }),
  syncErrors: localforage.createInstance({ name: 'hinov', storeName: 'syncErrors' }),
  syncMetadata: localforage.createInstance({ name: 'hinov', storeName: 'syncMetadata' }),
  // POS
  posCategories: localforage.createInstance({ name: 'hinov', storeName: 'posCategories' }),
  posBrands: localforage.createInstance({ name: 'hinov', storeName: 'posBrands' }),
  posSuppliers: localforage.createInstance({ name: 'hinov', storeName: 'posSuppliers' }),
  posProducts: localforage.createInstance({ name: 'hinov', storeName: 'posProducts' }),
  posStockEntries: localforage.createInstance({ name: 'hinov', storeName: 'posStockEntries' }),
  posInventories: localforage.createInstance({ name: 'hinov', storeName: 'posInventories' }),
  posCashSessions: localforage.createInstance({ name: 'hinov', storeName: 'posCashSessions' }),
  posTransactions: localforage.createInstance({ name: 'hinov', storeName: 'posTransactions' }),
  posPayments: localforage.createInstance({ name: 'hinov', storeName: 'posPayments' }),
  posDiscounts: localforage.createInstance({ name: 'hinov', storeName: 'posDiscounts' }),
  posSettings: localforage.createInstance({ name: 'hinov', storeName: 'posSettings' }),
  posReturns: localforage.createInstance({ name: 'hinov', storeName: 'posReturns' }),
  posStockMovements: localforage.createInstance({ name: 'hinov', storeName: 'posStockMovements' }),
  productCompletions: localforage.createInstance({ name: 'hinov', storeName: 'productCompletions' }),
  importSessions: localforage.createInstance({ name: 'hinov', storeName: 'importSessions' }),
  importErrors: localforage.createInstance({ name: 'hinov', storeName: 'importErrors' }),
  productImages: localforage.createInstance({ name: 'hinov', storeName: 'productImages' }),
  // CRM Documents
  documents: localforage.createInstance({ name: 'hinov', storeName: 'documents' }),
  documentFiles: localforage.createInstance({ name: 'hinov', storeName: 'documentFiles' }),
};
